### ISSUE TITLE
Sameboy core fails to build

### ISSUE THREAD

**Issue by lostfictions** [libretro/libretro-super#840]
I wanted to install the Sameboy core, but noticed it's not published in the [libretro "stable" PPA](https://launchpad.net/~libretro/+archive/ubuntu/stable/) for Ubuntu (though it seems to be in [testing](https://launchpad.net/~libretro/+archive/ubuntu/testing/).)

I thought I'd try to build it myself; I followed the instructions [here](https://docs.libretro.com/compilation/ubuntu/#core-compilation) to fetch and build the individual core. At first it failed because I didn't have the rgbds tools on my path, but checking the [SameBoy](https://github.com/libretro/SameBoy) repo I fixed that quickly. But it failed again after that, and I'm not too sure why; I can't really spot any obvious errors besides the one at the end. Digging into the Sameboy repo the fetch script cloned, `sameboy_libretro.so` seems to have built just fine, so maybe it's not grabbing it from the right place...?

```
PLATFORM: Linux
ARCHITECTURE: x86_64
TARGET: unix
CC = gcc
CXX = g++
CXX11 = g++
STRIP = 
Compiler: CC="gcc" CXX="g++"
=== x86 CPU detected... ===
=== x86_64 CPU detected... ===
unix
unix
=== SameBoy
Building sameboy...
cd "/home/s/Clones/libretro-super/libretro-sameboy/libretro"
make -f Makefile platform="unix" -j4  clean
rm -f ../build/obj/../Core/gb_libretro.c.o ../build/obj/../Core/apu_libretro.c.o ../build/obj/../Core/memory_libretro.c.o ../build/obj/../Core/mbc_libretro.c.o ../build/obj/../Core/timing_libretro.c.o ../build/obj/../Core/display_libretro.c.o ../build/obj/../Core/symbol_hash_libretro.c.o ../build/obj/../Core/camera_libretro.c.o ../build/obj/../Core/z80_cpu_libretro.c.o ../build/obj/../Core/joypad_libretro.c.o ../build/obj/../Core/save_state_libretro.c.o ../build/obj/../libretro/agb_boot_libretro.c.o ../build/obj/../libretro/cgb_boot_libretro.c.o ../build/obj/../libretro/dmg_boot_libretro.c.o ../build/obj/../libretro/libretro_libretro.c.o ../build/bin/sameboy_libretro.so
make -f Makefile platform="unix" -j4 CC="gcc" CXX="g++" 
gcc -c -o ../build/obj/../Core/gb_libretro.c.o ../Core/gb.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
gcc -c -o ../build/obj/../Core/apu_libretro.c.o ../Core/apu.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
gcc -c -o ../build/obj/../Core/memory_libretro.c.o ../Core/memory.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
gcc -c -o ../build/obj/../Core/mbc_libretro.c.o ../Core/mbc.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
../Core/apu.c: In function ‘update_sample’:
../Core/apu.c:44:9: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         if (*(uint32_t *)&(gb->apu_output.current_sample[index]) != *(uint32_t *)&output) {
         ^
../Core/apu.c:44:9: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
../Core/gb.c: In function ‘GB_is_inited’:
../Core/gb.c:417:25: warning: multi-character character constant [-Wmultichar]
     return gb->magic == 'SAME';
                         ^
../Core/gb.c: In function ‘GB_reset’:
../Core/gb.c:493:28: warning: multi-character character constant [-Wmultichar]
     gb->magic = (uintptr_t)'SAME';
                            ^
../Core/gb.c: In function ‘GB_attributed_logv’:
../Core/gb.c:22:5: warning: ignoring return value of ‘vasprintf’, declared with attribute warn_unused_result [-Wunused-result]
     vasprintf(&string, fmt, args);
     ^
../Core/gb.c: In function ‘GB_load_boot_rom’:
../Core/gb.c:156:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(gb->boot_rom, sizeof(gb->boot_rom), 1, f);
     ^
../Core/gb.c: In function ‘GB_load_rom’:
../Core/gb.c:191:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(gb->rom, gb->rom_size, 1, f);
     ^
gcc -c -o ../build/obj/../Core/timing_libretro.c.o ../Core/timing.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
gcc -c -o ../build/obj/../Core/display_libretro.c.o ../Core/display.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
gcc -c -o ../build/obj/../Core/symbol_hash_libretro.c.o ../Core/symbol_hash.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
gcc -c -o ../build/obj/../Core/camera_libretro.c.o ../Core/camera.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
gcc -c -o ../build/obj/../Core/z80_cpu_libretro.c.o ../Core/z80_cpu.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
gcc -c -o ../build/obj/../Core/joypad_libretro.c.o ../Core/joypad.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
../Core/z80_cpu.c: In function ‘add_hl_rr’:
../Core/z80_cpu.c:340:31: warning: suggest parentheses around ‘+’ in operand of ‘&’ [-Wparentheses]
     if ( ((unsigned long) hl) + ((unsigned long) rr) & 0x10000) {
                               ^
gcc -c -o ../build/obj/../Core/save_state_libretro.c.o ../Core/save_state.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
make -C .. build/bin/BootROMs/agb_boot.bin
make[1]: Entering directory '/home/s/Clones/libretro-super/libretro-sameboy'
cd BootROMs && rgbasm -o ../build/bin/BootROMs/agb_boot.bin.tmp ../BootROMs/agb_boot.asm
rgblink -o build/bin/BootROMs/agb_boot.bin.tmp2 build/bin/BootROMs/agb_boot.bin.tmp
head -c  2304 build/bin/BootROMs/agb_boot.bin.tmp2 > build/bin/BootROMs/agb_boot.bin
make[1]: Leaving directory '/home/s/Clones/libretro-super/libretro-sameboy'
make -C .. build/bin/BootROMs/cgb_boot.bin
make[1]: Entering directory '/home/s/Clones/libretro-super/libretro-sameboy'
cd BootROMs && rgbasm -o ../build/bin/BootROMs/cgb_boot.bin.tmp ../BootROMs/cgb_boot.asm
rgblink -o build/bin/BootROMs/cgb_boot.bin.tmp2 build/bin/BootROMs/cgb_boot.bin.tmp
head -c  2304 build/bin/BootROMs/cgb_boot.bin.tmp2 > build/bin/BootROMs/cgb_boot.bin
make[1]: Leaving directory '/home/s/Clones/libretro-super/libretro-sameboy'
make -C .. build/bin/BootROMs/dmg_boot.bin
make[1]: Entering directory '/home/s/Clones/libretro-super/libretro-sameboy'
cd BootROMs && rgbasm -o ../build/bin/BootROMs/dmg_boot.bin.tmp ../BootROMs/dmg_boot.asm
rgblink -o build/bin/BootROMs/dmg_boot.bin.tmp2 build/bin/BootROMs/dmg_boot.bin.tmp
head -c  256 build/bin/BootROMs/dmg_boot.bin.tmp2 > build/bin/BootROMs/dmg_boot.bin
make[1]: Leaving directory '/home/s/Clones/libretro-super/libretro-sameboy'
gcc -c -o ../build/obj/../libretro/libretro_libretro.c.o ../libretro/libretro.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
echo "/* AUTO-GENERATED */" > ../libretro/agb_boot.c
echo "const unsigned char agb_boot[] = {" >> ../libretro/agb_boot.c
hexdump -v -e '/1 "0x%02x, "' ../build/bin/BootROMs/agb_boot.bin >> ../libretro/agb_boot.c
echo "};" >> ../libretro/agb_boot.c
echo "const unsigned agb_boot_length = sizeof(agb_boot);" >> ../libretro/agb_boot.c
echo "/* AUTO-GENERATED */" > ../libretro/cgb_boot.c
echo "const unsigned char cgb_boot[] = {" >> ../libretro/cgb_boot.c
hexdump -v -e '/1 "0x%02x, "' ../build/bin/BootROMs/cgb_boot.bin >> ../libretro/cgb_boot.c
echo "};" >> ../libretro/cgb_boot.c
echo "const unsigned cgb_boot_length = sizeof(cgb_boot);" >> ../libretro/cgb_boot.c
echo "/* AUTO-GENERATED */" > ../libretro/dmg_boot.c
echo "const unsigned char dmg_boot[] = {" >> ../libretro/dmg_boot.c
hexdump -v -e '/1 "0x%02x, "' ../build/bin/BootROMs/dmg_boot.bin >> ../libretro/dmg_boot.c
echo "};" >> ../libretro/dmg_boot.c
echo "const unsigned dmg_boot_length = sizeof(dmg_boot);" >> ../libretro/dmg_boot.c
gcc -c -o ../build/obj/../libretro/agb_boot_libretro.c.o ../libretro/agb_boot.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
gcc -c -o ../build/obj/../libretro/cgb_boot_libretro.c.o ../libretro/cgb_boot.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
gcc -c -o ../build/obj/../libretro/dmg_boot_libretro.c.o ../libretro/dmg_boot.c -DGIT_VERSION=\"" 5ab6b5b"\" -DSAMEBOY_CORE_VERSION=\"\" -O2 -DNDEBUG -DDISABLE_TIMEKEEPING -DDISABLE_REWIND -DDISABLE_DEBUGGER -Wall -D__LIBRETRO__ -fPIC -I.. -std=gnu11 -D_GNU_SOURCE -D_USE_MATH_DEFINES -fPIC -DGB_INTERNAL
gcc -fPIC -shared -Wl,--version-script=../libretro/link.T -Wl,--no-undefined -I.. -o ../build/bin/sameboy_libretro.so ../build/obj/../Core/gb_libretro.c.o ../build/obj/../Core/apu_libretro.c.o ../build/obj/../Core/memory_libretro.c.o ../build/obj/../Core/mbc_libretro.c.o ../build/obj/../Core/timing_libretro.c.o ../build/obj/../Core/display_libretro.c.o ../build/obj/../Core/symbol_hash_libretro.c.o ../build/obj/../Core/camera_libretro.c.o ../build/obj/../Core/z80_cpu_libretro.c.o ../build/obj/../Core/joypad_libretro.c.o ../build/obj/../Core/save_state_libretro.c.o ../build/obj/../libretro/agb_boot_libretro.c.o ../build/obj/../libretro/cgb_boot_libretro.c.o ../build/obj/../libretro/dmg_boot_libretro.c.o ../build/obj/../libretro/libretro_libretro.c.o -lm
rm ../libretro/cgb_boot.c ../build/bin/BootROMs/cgb_boot.bin ../libretro/dmg_boot.c ../build/bin/BootROMs/dmg_boot.bin ../libretro/agb_boot.c ../build/bin/BootROMs/agb_boot.bin
cp "sameboy_libretro.so" "/home/s/Clones/libretro-super/dist/unix/sameboy_libretro.so"
cp: cannot stat 'sameboy_libretro.so': No such file or directory
1 core(s) failed:
   sameboy
```

**Comment by hizzlekizzle** [comment]
looks like it's just not getting named properly. Can you look in your source tree and see what the resulting library is actually named?

**Comment by lostfictions** [comment]
Looks like it got built as `libretro-sameboy/build/bin/sameboy_libretro.so`, but I can clean up build artefacts and try to build again later today just to double-check...

**Comment by orbea** [comment]
Is this fixed now for you? I can't reproduce it with the master.

**Comment by lostfictions** [comment]
@orbea I pulled master and tried again, but it's still happening for me. It seems to be building the library correctly but not finding the .so, so the build script fails (but I can grab the .so myself at that point and put it where it needs to go.)

**Comment by fr500** [comment]
you have to build the buildbot branch and from within the libretro folder

**Comment by lostfictions** [comment]
So are the instructions here wrong? https://docs.libretro.com/compilation/ubuntu/#core-compilation
